### DISCUSSION TITLE
Raspberry PI compatibility

### DISCUSSION THREAD

**Discussion by ziadsarour** [chatwoot/chatwoot#2361] [Self hosted] [answered]
Hello,

It would be great if we could deploy Chatwoot on a Raspberry PI.
I think it would be difficult because of the mailhog image, but it can be really cool to have a self hosted version on a Raspberry PI !

BTW thank you for this project, you're awesome ✌️

**Comment by pranavrajs** [comment, marked as answer]
@ziadsarour Mailhog is only required in development env. Please see the production env here. https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml

**Comment by Startouf** [comment]
Hello @pranavrajs I'm trying to setup chatwoot on a raspberry pi 4 and I have the following errors on various related services

> exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error
> exec /bin/bash: exec format error
> exec /usr/local/bundle/bin/bundle: exec format error

It seems like many dependencies used are not compatible with the Raspberry pi architecture ? 
Or maybe we just need to provide different image tage for the dependencies ?

EDIT : it also affects the main image(s) used by chatwoot with rails :'(

**Comment by Startouf** [comment]
I was able to solve the dependencies issues by switching to docker ARM repositories. Unfortunately they do not provide all image tags, so we have to override the tag key and it will need to be updated with each chatwoot release :'(

```
# values/chatwoot.yaml
postgresql:
  image:
    # Pick an ARM Compatible image
    repository: arm32v7/postgres
    tag: 14.4
redis:
  image:
    # Pick an ARM Compatible image
    repository: arm32v7/redis
    tag: 6.2
```

However the chatwoot docker repo does not seem to have ARM images, so I guess we'll have to build the chatwoot images manually :'(
