### DISCUSSION TITLE
Installation on Openshift 4

### DISCUSSION THREAD

**Discussion by markamber** [chatwoot/chatwoot#5106] [Self hosted]
Hello, 

I am installing on Openshift, a very security constrained environment! I am using the helm chart.

I am getting this in the console log for the [release]-chatwoot-web Pod.

```
/usr/local/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /app/tmp/cache (Errno::EACCES)
```

I did try these security values, as well as some slight tweaks to them...

```
podSecurityContext:
  fsGroup: 1000810000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000810000
```

in this context, 1000810000 is the first gid/uid in my environment.

I can see this security spec being applied to the pods:

```
spec:
  securityContext:
    seLinuxOptions:
      level: 's0:c28,c27'
    fsGroup: 1000810000
  containers:
    - resources: {}
      name: chatwoot-workers
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000810000
```

I'm really not sure what I am doing here. 

My openshift is version 4.10.0-0.okd-2022-06-24-212905
