### DISCUSSION TITLE
RedisClient::CannotConnectError: Connection refused

### DISCUSSION THREAD

**Discussion by fabr2004** [chatwoot/chatwoot#9495] [Self hosted] [answered]
I have Chatwoot recently installed on premise.
When I manually start (`docker compose up -d`) it runs fine.
When I reboot the container I get the error below.
And, interestingly, if I manually stop (`docker compose down`) and then manually start it runs fine again.
How to solve this?

**Log from `chatwoot-sidekiq-1`:**
```
{"ts":"2024-05-17T21:19:25.197Z","pid":1,"tid":"5hzt","lvl":"WARN","msg":""}
{"ts":"2024-05-17T21:19:25.182Z","pid":1,"tid":"5ij9","lvl":"ERROR","msg":"Error fetching job: Connection refused - connect(2) for 172.18.0.3:6379"}
{"ts":"2024-05-17T21:19:25.197Z","pid":1,"tid":"5ij9","lvl":"WARN","msg":"RedisClient::CannotConnectError: Connection refused - connect(2) for 172.18.0.3:6379 (redis://redis:6379)"}
{"ts":"2024-05-17T21:19:25.198Z","pid":1,"tid":"5ij9","lvl":"WARN","msg":""}
{"ts":"2024-05-17T21:19:25.579Z","pid":1,"tid":"5kkl","lvl":"INFO","msg":"Pausing to allow jobs to finish..."}
{"ts":"2024-05-17T21:19:26.610Z","pid":1,"tid":"5b5","lvl":"INFO","msg":"Bye!"}
```

**Versions:**
```
docker --version
Docker version 26.1.3, build b72abbb

docker compose version
Docker Compose version v2.27.0

Chatwoot v3.9.0
Build f7580f864c837a0e5efa39fe3696e7a224327e11
```

**Docker compose:**

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xxx

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - /data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
```
