### ISSUE TITLE
Messages are queued in Sidekiq but not executed

### ISSUE THREAD

**Issue by angelhodar** [chatwoot/chatwoot#10130]
### Describe the bug

Hi! I am testing a self hosted instance of chatwoot and I have setup a Telegram bot and channel because its very quick to setup. Everything seems to be correctly configured, messages are coming to the webhook and they are registered in Sidekiq. The problem is that they get in queue but not executed, so chat UI is not updated. After some investigation I see that the service container for sidekiq in my compose exits after some time. I am using Dokploy to setup everything, I will show you the services and the logs.

### To Reproduce

1. To simplify the compose, I have moved the redis and postgres db to another containers. It looks like this in dokploy:
![image](https://github.com/user-attachments/assets/793e89c4-ce16-41f3-914b-b846e51f29e1)

2. Add this minimal compose to app service:

```
services:
  chatwoot:
    image: chatwoot/chatwoot:latest
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY
      - FRONTEND_URL=$FRONTEND_URL
      - DEFAULT_LOCALE=en
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - DATABASE_URL=$DATABASE_URL
      - RAILS_MAX_THREADS=5
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=local
    entrypoint: docker/entrypoints/rails.sh
    command: sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - rails-data:/app/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 5s
      timeout: 20s
      retries: 10

  sidekiq:
    image: chatwoot/chatwoot:latest
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY
      - FRONTEND_URL=$FRONTEND_URL
      - DEFAULT_LOCALE=en
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - DATABASE_URL=$DATABASE_URL
      - RAILS_MAX_THREADS=5
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - ACTIVE_STORAGE_SERVICE=local
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    volumes:
      - sidekiq-data:/app/storage

volumes:
  rails-data:
  sidekiq-data:

networks:
  dokploy-network:
    external: true
```

3. I have added this env vars:

```
FRONTEND_URL=https://chatwoot.angelhodar.com
SECRET_KEY=atsdvasdvgasdas9nas9unchygat7sdfas5dfas
REDIS_URL=redis://default@chatwoot-redis-68144c:6379
REDIS_PASSWORD=<REDACTED>
DATABASE_URL=postgresql://postgres:<REDACTED>@chatwoot-postgres-0e9995:5432/chatwoot
```

4. And the app works perfectly:

![image](https://github.com/user-attachments/assets/6ffc24fa-166b-4715-95d1-c6befb4e4f95)

5. But if I go to the super admin console, the sidekiq dashboard is working (should it if the sidekiq process is exited??) and I see this, so the message is arriving the server but just gets queued:

![image](https://github.com/user-attachments/assets/59468ccc-4f1f-4caf-8749-a245fa694f3a)

6. These are the logs from the sidekiq process:

![image](https://github.com/user-attachments/assets/8cd40be2-c728-475b-813d-226a6558a231)

![image](https://github.com/user-attachments/assets/3e56aa52-4fe5-4e82-b044-ef5e7c0f7fe7)

### Expected behavior

Sidekiq jobs should be executed

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Additional context

I am testing this in a Hetzner Intel x86 server.
