### ISSUE TITLE
500 Internal Server Error while sing in

### ISSUE THREAD

**Issue by vitaleg** [chatwoot/chatwoot#10188]
### Describe the bug

```
rails-1     | I, [2024-09-29T15:48:18.725782 #1]  INFO -- : [b91c37ed-aed2-402c-b973-19a579850f5a] Started POST "/auth/sign_in" for 10.76.99.2 at 2024-09-29 15:48:18 +0000
rails-1     | I, [2024-09-29T15:48:18.727497 #1]  INFO -- : [b91c37ed-aed2-402c-b973-19a579850f5a] Processing by DeviseOverrides::SessionsController#create as HTML
rails-1     | I, [2024-09-29T15:48:18.727522 #1]  INFO -- : [b91c37ed-aed2-402c-b973-19a579850f5a]   Parameters: {"email"=>"user@example.com", "password"=>"[FILTERED]", "sso_auth_token"=>"[FILTERED]"}
rails-1     | I, [2024-09-29T15:48:18.881366 #1]  INFO -- : [b91c37ed-aed2-402c-b973-19a579850f5a] Completed 500 Internal Server Error in 154ms (ActiveRecord: 5.1ms | Allocations: 8435)
rails-1     | F, [2024-09-29T15:48:18.882083 #1] FATAL -- : [b91c37ed-aed2-402c-b973-19a579850f5a]   
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] ActionView::Template::Error (undefined method `custom_role_id' for an instance of AccountUser):
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a]     1: json.custom_role_id account_user&.custom_role_id
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a]     2: json.custom_role account_user&.custom_role&.as_json(only: [:id, :name, :description, :permissions])
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a]   
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/views/api/v1/models/_user.json.jbuilder:33
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/views/api/v1/models/_user.json.jbuilder:21
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/views/api/v1/models/_user.json.jbuilder:20
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/views/devise/_auth.json.jbuilder:2
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/views/devise/_auth.json.jbuilder:1
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/controllers/devise_overrides/sessions_controller.rb:23:in `render_create_success'
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/controllers/devise_overrides/sessions_controller.rb:18:in `create'
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails-1     | [b91c37ed-aed2-402c-b973-19a579850f5a] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'
rails-1     | I, [2024-09-29T15:48:18.882204 #1]  INFO -- : source=rack-timeout id=b91c37ed-aed2-402c-b973-19a579850f5a timeout=15000ms service=157ms state=completed
```

### To Reproduce

The problem is reproduced during an authentication attempt.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Docker (if applicable)

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - ./data/storage:/app/storage
      - ./ca-certificates:/usr/local/share/ca-certificates
    restart: always
  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=7SjioKJFndw7BrVQ7xn4jcusG
  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
```
