### ISSUE TITLE
Bug chat live

### ISSUE THREAD

**Issue by Kowalsky98** [chatwoot/chatwoot#10487]
### Describe the bug

I have an error or a bug so to speak, I am trying to use chatwoot together with portainer and caddy to manage the reverse proxy, my problem in question is that when using the live chat, it does not update automatically beyond that No log shows an error or communication problems, neither in the browser console nor anywhere does the error appear. The strangest thing is that when the chat starts the status changes to ONLINE but the chat is not updated unless I reloaded both web pages, I leave my docker-compose.yml in case it helps

### To Reproduce

![Captura de pantalla 2024-11-22 114722](https://github.com/user-attachments/assets/d037f7d9-f439-4316-b583-c67a5fb47279)

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Linux

### Browser and version

Chrome

### Docker (if applicable)

version: "3.9"

networks:
  caddy:
    external: true
  chatwoot:
    name: chatwoot_network
    driver: bridge

volumes:
  chatwoot_storage:
    name: chatwoot_storage_data
  chatwoot_public:
    name: chatwoot_public_data
  chatwoot_mailer:
    name: chatwoot_mailer_views
  chatwoot_mailers:
    name: chatwoot_mailers_views
  chatwoot_cache:
    name: chatwoot_cache_data
  bundle:
    name: chatwoot_bundle
  postgres:
    name: postgres_data
  redis_data:
    name: redis_persistent_data

services:
  rails:
    image: chatwoot/chatwoot:v3.15.0
    depends_on:
      postgres-chatwoot:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
      - chatwoot_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    labels:
      - caddy=${FRONTEND_URL}
      - caddy.reverse_proxy=/cable/* rails:3000
      - caddy.reverse_proxy="{{upstreams 3000}}"

    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      RAILS_LOG_TO_STDOUT: "true"
      ENABLE_PUSH_RELAY_SERVER: true
      USE_INBOX_AVATAR_FOR_BOT: "true"
      FORCE_SSL: "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ACTIVE_STORAGE_SERVICE: ${ACTIVE_STORAGE_SERVICE}
      DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres-chatwoot:5432/chatwoot
      REDIS_URL: redis://default:${REDIS_PASSWORD}@redis:6379
      DEFAULT_LOCALE: ${DEFAULT_LOCALE}
      ENABLE_ALPINE_PRIVATE_NETWORKING: ${ENABLE_ALPINE_PRIVATE_NETWORKING}
      MAILER_SENDER_EMAIL: ${MAILER_SENDER_EMAIL}
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_AUTHENTICATION: login
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SSL: "true"
      SMTP_USERNAME: ${SMTP_USERNAME}
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: unless-stopped
    networks:
      - caddy
      - chatwoot

  sidekiq:
    image: chatwoot/chatwoot:v3.15.0
    depends_on:
      postgres-chatwoot:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres-chatwoot:5432/chatwoot
      REDIS_URL: redis://default:${REDIS_PASSWORD}@redis:6379
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: unless-stopped
    networks:
      - chatwoot

  postgres-chatwoot:
    image: postgres:14.7-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - chatwoot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - chatwoot
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

### Additional context

As a curious fact, when it was set up as a service from railway, everything worked correctly

**Comment by pranavrajs** [comment]
@Kowalsky98 The real-time messages aren’t working. The possible reasons for this issue could be any network configuration issues in your infrastructure or problems with the Sidekiq workers. It’s also possible that these factors are combined. 

Since we don’t support Portainer ourselves, we can’t assist in further debugging. The best course of action would be to start checking the browser logs first to see if you find any relevant information.

**Comment by Kowalsky98** [comment]
In case it is useful to anyone, you can solve the problem by correcting docker-compose as follows, Using Portainer and Caddy for Reverse Proxy Handling:

```
networks:
  caddy:
    external: true
  chatwoot:
    name: chatwoot_network
    driver: bridge

volumes:
  chatwoot_storage:
    name: chatwoot_storage_data
  chatwoot_public:
    name: chatwoot_public_data
  chatwoot_mailer:
    name: chatwoot_mailer_views
  chatwoot_mailers:
    name: chatwoot_mailers_views
  chatwoot_cache:
    name: chatwoot_cache_data
  bundle:
    name: chatwoot_bundle
  postgres:
    name: postgres_data
  redis_data:
    name: redis_persistent_data

services:
  base: &base
    image: chatwoot/chatwoot:v3.15.0-ce
    env_file: stack.env ## Change this file for customized env variables
    volumes:
      - chatwoot_storage:/app/storage
      - chatwoot_public:/app/public
      - chatwoot_mailer:/app/app/views/devise/mailer
      - chatwoot_mailers:/app/app/views/mailers
      - chatwoot_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    networks:
      - chatwoot

  rails:
    <<: *base
    depends_on:
      postgres-chatwoot:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - caddy=${FRONTEND_URL}
      - caddy.reverse_proxy=/cable/* rails:3000
      - caddy.reverse_proxy="{{upstreams 3000}}"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    networks:
      - caddy
      - chatwoot

  sidekiq:
    <<: *base
    depends_on:
      - postgres-chatwoot
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
    networks:
      - chatwoot

  postgres-chatwoot:
    image: postgres:14.7-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - chatwoot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - chatwoot
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
```
