### ISSUE TITLE
how to use webpack docker?

### ISSUE THREAD

**Issue by lybtt** [chatwoot/chatwoot#1189]
hi, I used docker-compose -f docker-compose.production.yaml up run chatwoot.

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables

  rails:
    <<: *base
    ports:
      - 3000:3000
    network_mode: host
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    network_mode: host
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
```

The deployment process was very difficult，but fortunately, it worked.

Then, I create a inbox in the web app, and I copy the code to my website.
```js
<script>
  (function(d,t) {
    var BASE_URL = "http://my-url:3000";
    var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src= BASE_URL + "/packs/js/sdk.js";
    s.parentNode.insertBefore(g,s);
    g.onload=function(){
      window.chatwootSDK.run({
        websiteToken: '31a36QNsnpzr4rsxEG2uqar1',
        baseUrl: BASE_URL
      })
    }
  })(document,"script");
</script>
```
I get the error, no-referrer-when-downgrade.

I check the /packs/js/sdk.js,  No such file or directory.

So maybe I need webpack first? what should I do?
