### ISSUE TITLE
yaml key duplication results in not all calls appearing in API docs

### ISSUE THREAD

**Issue by ktyborowski** [chatwoot/chatwoot#1498]
I've noticed that some duplicate keys appear in the swagger paths yaml files. This results in only one of the duplicated calls appearing in the final swagger.json.

Some examples of this:
https://github.com/chatwoot/chatwoot/blob/2880f4942a03a4a4ee40b023d00ae24da99e8ab7/swagger/paths/index.yml#L4-L8

https://github.com/chatwoot/chatwoot/blob/2880f4942a03a4a4ee40b023d00ae24da99e8ab7/swagger/paths/conversation/index_or_create.yml#L1-L81

Possible solution for the first instance of the issue:
````
# Inboxes
/accounts/{account_id}/inboxes:
  get:
    $ref: ./inboxes/index.yml
  post:
    $ref: ./inboxes/create.yml
````
The second one is more difficult since I don't think swagger can differentiate between two GET calls with different query parameters and request bodies. This could possibly require a change in the API path.
