### ISSUE TITLE
Cannot scroll on mobile view if campaign is active

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2545]
Issues:

- Cannot scroll the website if the campaign is active
- The position of the campaign message is random
- Cannot see the close button

<img width="450" alt="Screenshot 2021-06-29 at 9 51 47 PM" src="https://user-images.githubusercontent.com/2246121/123833759-4f743d00-d924-11eb-889c-cf5264e7bb09.png">

**Comment by AllanJard** [comment]
I'm seeing this as well. It is due to https://github.com/chatwoot/chatwoot/blob/1d3b1c1ae55333c3df1c45d0989e81026b8eff01/app/javascript/sdk/sdk.js#L123 - which is basically just taking the whole screen when there is a notification about a new message.

```css
@media only screen and (max-width: 667px) {
  .woot-widget-holder {
    height: auto;
     right: 0;
    top: auto;
    width: auto;
    bottom: 0;
  }
}
```

Works around it by letting it just take what height and width it needs (still a little too much width really, but better).
