### ISSUE TITLE
Dialogflow integration not working

### ISSUE THREAD

**Issue by gerardbrunoquantion** [chatwoot/chatwoot#2609]
**Describe the bug**

I have configured a Dialogflow hook but it's not working as expected. Chatwoot categorizes the conversation under the "bot" tag but Dialogflow responses does never reach the chat.

**To Reproduce**

1. Create a web inbox.
2. Follow the instructions given in the [official docs](https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow).
3. Send "hello" message over the chat.

**Expected behavior**

Chatwoot should get the response from Dialogflow and respond to the chat.

**Server logs**

> ERROR -- : [ActiveJob] [HookJob] [bf31ccb2-fd40-4085-8960-647826c15951] Error performing HookJob (Job ID: bf31ccb2-fd40-4085-8960-647826c15951) from Sidekiq(integrations) in 8.14ms: LoadError (Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so) - /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so):

```
{
  "context": "Job raised exception",
  "job": {
    "retry": true,
    "queue": "integrations",
    "class": "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "wrapped": "HookJob",
    "args": [
      {
        "job_class": "HookJob",
        "job_id": "178a8d5c-2d30-477e-99e7-f23c1826874a",
        "provider_job_id": null,
        "queue_name": "integrations",
        "priority": null,
        "arguments": [
          {
            "_aj_globalid": "gid://chatwoot/Integrations::Hook/6"
          },
          "message.created",
          {
            "message": {
              "_aj_globalid": "gid://chatwoot/Message/77"
            },
            "_aj_ruby2_keywords": [
              "message"
            ]
          }
        ],
        "executions": 0,
        "exception_executions": {},
        "locale": "en",
        "timezone": "UTC",
        "enqueued_at": "2021-07-14T10:16:53Z"
      }
    ],
    "jid": "d245e74c5b2fafb917fbaa51",
    "created_at": 1626257813.5812998,
    "enqueued_at": 1626257831.8023748,
    "error_message": "Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so) - /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so",
    "error_class": "LoadError",
    "failed_at": 1626257813.7213137,
    "retry_count": 0
  },
  "jobstr": "{\"retry\":true,\"queue\":\"integrations\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"HookJob\",\"args\":[{\"job_class\":\"HookJob\",\"job_id\":\"178a8d5c-2d30-477e-99e7-f23c1826874a\",\"provider_job_id\":null,\"queue_name\":\"integrations\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://chatwoot/Integrations::Hook/6\"},\"message.created\",{\"message\":{\"_aj_globalid\":\"gid://chatwoot/Message/77\"},\"_aj_ruby2_keywords\":[\"message\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-07-14T10:16:53Z\"}],\"jid\":\"d245e74c5b2fafb917fbaa51\",\"created_at\":1626257813.5812998,\"enqueued_at\":1626257831.8023748,\"error_message\":\"Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so) - /gems/ruby/2.7.0/gems/grpc-1.37.1-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so\",\"error_class\":\"LoadError\",\"failed_at\":1626257813.7213137,\"retry_count\":0}"
}
```

**Environment**
Self hosted deployed with Docker.

**Additional context**

For some reason, when i configure the Dialogflow Hook, the integration status is "disabled":
![image](https://user-images.githubusercontent.com/17406175/125282298-83356680-e317-11eb-84f1-0ae5713e86e6.png)

**Comment by DevS1993** [comment]
I have faced this issue. It is related to a library that is needed in google-protobuf. Can you share your Dockerfile?

**Comment by gerardbrunoquantion** [comment]
I am not using any Dockerfile. I use the images on Docker Hub in my docker-compose.yml as follows:

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    # restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=--

  redis:
    image: redis:alpine
    # restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis-volume:/data
    # ports:
    #   - '6379:6379'

volumes:
  redis-volume:
  postgres-volume:
```
