### ISSUE TITLE
I don't receive incoming emails on my email channel

### ISSUE THREAD

**Issue by johackim** [chatwoot/chatwoot#2712]
**Describe the bug**

I setup Chatwoot with docker and I don't receive incoming emails on my email channel.

**To Reproduce**

Here my configuration :

```yaml
version: '3.7'

x-defaults: &defaults
  environment:
    - SECRET_KEY_BASE=${SECRET_KEY_BASE:-"replace_with_lengthy_secure_hex"}
    - FRONTEND_URL=${SCHEME:-http}://${DOMAIN:-chatwoot.localhost}
    - NODE_ENV=${NODE_ENV:-production}
    - RAILS_ENV=${RAILS_ENV:-production}
    - POSTGRES_HOST=postgres
    - POSTGRES_USERNAME=chatwoot
    - POSTGRES_DATABASE=chatwoot
    - POSTGRES_PASSWORD=myp@ssw0rd
    - REDIS_URL=redis://redis:6379
    - REDIS_PASSWORD=myp@ssw0rd
    - SMTP_ADDRESS=${SMTP_ADDRESS}
    - SMTP_AUTHENTICATION=plain
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_ENABLE_STARTTLS_AUTO=true
    - SMTP_PORT=${SMTP_PORT:-587}
    - SMTP_USERNAME=${SMTP_USERNAME}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - RAILS_INBOUND_EMAIL_SERVICE=relay
    - MAILER_INBOUND_EMAIL_DOMAIN=${MAILER_INBOUND_EMAIL_DOMAIN}
    - RAILS_INBOUND_EMAIL_PASSWORD=${RAILS_INBOUND_EMAIL_PASSWORD}
    - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-s3_compatible}
    - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
    - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
    - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
    - STORAGE_REGION=${STORAGE_REGION:-us-east-1}
    - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
    - STORAGE_FORCE_PATH_STYLE=${STORAGE_FORCE_PATH_STYLE:-false}

services:
  web:
    <<: *defaults
    image: chatwoot/chatwoot:${VERSION:-v1.18.1}
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot-${NUMBER:-1}.rule=Host(`${DOMAIN:-chatwoot.localhost}`)
        - traefik.http.routers.chatwoot-${NUMBER:-1}.entrypoints=${SCHEME:-http}
        - traefik.http.routers.chatwoot-${NUMBER:-1}.service=chatwoot-${NUMBER:-1}
        - traefik.http.routers.chatwoot-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.chatwoot-${NUMBER:-1}.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik

  sidekiq:
    <<: *defaults
    image: chatwoot/chatwoot:${VERSION:-v1.18.1}
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    networks:
      - internal

  redis:
    <<: *defaults
    image: redis:alpine
    command: /bin/sh -c 'redis-server --requirepass $$REDIS_PASSWORD'
    networks:
      - internal

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=chatwoot
      - POSTGRES_PASSWORD=myp@ssw0rd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "chatwoot"]
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
```

I have an IMAP and SMTP server with [docker-mailserver](https://github.com/docker-mailserver/docker-mailserver).

I read this "[tutorial](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity)" but I don't know how to setup this env vars : 

```
- RAILS_INBOUND_EMAIL_SERVICE=relay
- MAILER_INBOUND_EMAIL_DOMAIN=imap.server.com ??
- RAILS_INBOUND_EMAIL_PASSWORD=imap_password ??
```

Thanks for your help :)
