### ISSUE TITLE
Running chatwoot with docker in production is broken

### ISSUE THREAD

**Issue by kolaente** [chatwoot/chatwoot#299]
**Describe the bug**
I tried to run chatwoot with docker using the pre-built images and got a rails error about missing secrets:

```log
server_1    | => Booting Puma
server_1    | => Rails 6.0.1 application starting in production 
server_1    | => Run `rails server --help` for more startup options
server_1    | Exiting
server_1    | /usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:580:in `validate_secret_key_base': Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit` (ArgumentError)
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:423:in `secret_key_base'
server_1    | 	from /usr/local/bundle/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:24:in `key_exists?'
server_1    | 	from /usr/local/bundle/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:16:in `find'
server_1    | 	from /usr/local/bundle/gems/devise-4.7.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
server_1    | 	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
server_1    | 	from /app/config/environment.rb:5:in `<main>'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
server_1    | 	from config.ru:3:in `block in <main>'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
server_1    | 	from config.ru:in `new'
server_1    | 	from config.ru:in `<main>'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
server_1    | 	from /usr/local/bundle/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:39:in `start'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `tap'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/commands/server/server_command.rb:138:in `perform'
server_1    | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
server_1    | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
server_1    | 	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/command/base.rb:65:in `perform'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/command.rb:46:in `invoke'
server_1    | 	from /usr/local/bundle/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<main>'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
server_1    | 	from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
server_1    | 	from /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
server_1    | 	from bin/rails:4:in `<main>'
```

This is my docker-compose setup:

```yaml
version: '3'
services:

  server: 
    image: chatwoot/chatwoot
    restart: unless-stopped
    ports:
      - 3000:3000
      - 5000:5000
      - 3035:3035
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=secret
      - RAILS_ENV=production

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - ./db:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./db:/data/redis
```

**To Reproduce**

1. Copy the `docker-compose` file from above
2. Try to run it with `docker-compose up`

**Expected behavior**

It should not ask for secret keys via the console. Instead, these should be provided via some form of configuration. At best using env variables or similar.

**Additional Context**
I initially set `RAILS_ENV` to production because I could not pass the correct database credentials to the container otherwise, it kept using the default for development, which is empty. I assume this is configured in https://github.com/chatwoot/chatwoot/blob/master/config/database.yml#L11.

**Desktop (please complete the following information):**
 - OS: nixos 19.09

**Comment by sojan-official** [comment]
@kolaente you should be able to bypass this error by setting environment variable `SECRET_KEY_BASE`  with a value secure random hash value.  Apologize for the lack of documentation here, please leave this issue open. will close once add this to documentation. 
we will also update the database.yml to pick up the environment variable when provided as well. 

TODO 
------

- [ ] update database yml to use ENV variables and the  'empty value' as optional param
- [ ] update documentation to reflect that SECRET_KEY_BASE has to add as an environment variable 

cc: @pranavrajs  @sony-mathew

**Comment by kolaente** [comment]
@sojan-official Great, thanks!

Though now I get this when trying to access chatwoot with my browser:
![image](https://user-images.githubusercontent.com/13721712/69666321-5a9e2180-108c-11ea-93c2-bb4cfda25505.png)

Which makes sense, I assume in production mode, it won't show the logs to end users. Where are these logs stored?

**Comment by sojan-official** [comment]
@kolaente the logs should be in '/logs' folder.  

please also ref https://www.chatwoot.com/docs/quick-setup  [ Docker section ] 

you might need to run `docker-compose run server bundle exec rake db:reset` 
if the database set up wasn't done yet. 

let us know if you run into more issues.

**Comment by kolaente** [comment]
I took a look at the docs:

```
I, [2019-11-26T19:45:42.911774 #1]  INFO -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] Started GET "/" for 192.168.32.1 at 2019-11-26 19:45:42 +0000
I, [2019-11-26T19:45:42.912409 #1]  INFO -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] Processing by DashboardController#index as HTML
I, [2019-11-26T19:45:42.912872 #1]  INFO -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]   Rendering dashboard/index.html.erb within layouts/vueapp
I, [2019-11-26T19:45:42.912965 #1]  INFO -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.0ms | Allocations: 5)
I, [2019-11-26T19:45:42.913768 #1]  INFO -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] Completed 500 Internal Server Error in 1ms (Allocations: 794)
D, [2019-11-26T19:45:42.913848 #1] DEBUG -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] Webpacker can't find application in /app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-7eee80c25811c89cda9d.js",
  "application.js.map": "/packs/js/application-7eee80c25811c89cda9d.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-7eee80c25811c89cda9d.js"
      ],
      "js.map": [
        "/packs/js/application-7eee80c25811c89cda9d.js.map"
      ]
    },
    "sdk": {
      "js": [
        "/packs/js/sdk.js"
      ],
      "js.map": [
        "/packs/js/sdk.js.map"
      ]
    },
    "widget": {
      "js": [
        "/packs/js/widget-7eee80c25811c89cda9d.js"
      ],
      "js.map": [
        "/packs/js/widget-7eee80c25811c89cda9d.js.map"
      ]
    }
  },
  "media/dashboard/assets/images/agent.svg": "/packs/media/dashboard/assets/images/agent-aa76bb40e41e0e737cf0e929e8c66d20.svg",
  "media/dashboard/assets/images/canned.svg": "/packs/media/dashboard/assets/images/canned-87a4e4e0032b5b27557c494d9cf1fc2d.svg",
  "media/dashboard/assets/images/channels/facebook.png": "/packs/media/dashboard/assets/images/channels/facebook-4cbc901356e134d542a94a991cdbf4cf.png",
  "media/dashboard/assets/images/channels/facebook_login.png": "/packs/media/dashboard/assets/images/channels/facebook_login-cdbce77d96b5fe3ce2dc084764b4d5e9.png",
  "media/dashboard/assets/images/channels/line.png": "/packs/media/dashboard/assets/images/channels/line-15ace046ed5a35b4304b37d0c077b8e3.png",
  "media/dashboard/assets/images/channels/telegram.png": "/packs/media/dashboard/assets/images/channels/telegram-8967c418781f558f249f84faffbc8e02.png",
  "media/dashboard/assets/images/channels/twitter.png": "/packs/media/dashboard/assets/images/channels/twitter-fef946b8bba756359e2a1e87ccd915ea.png",
  "media/dashboard/assets/images/channels/website.png": "/packs/media/dashboard/assets/images/channels/website-2a4b439c3609ca48ab20c2714333ba77.png",
  "media/dashboard/assets/images/chat.svg": "/packs/media/dashboard/assets/images/chat-55f282b2485b821d927f5228722f48af.svg",
  "media/dashboard/assets/images/fb-badge.png": "/packs/media/dashboard/assets/images/fb-badge-7a4add817f6e7fe207ffe52c428f3305.png",
  "media/dashboard/assets/images/flag.svg": "/packs/media/dashboard/assets/images/flag-10c114599f84077e6edf5f3def7f8855.svg",
  "media/dashboard/assets/images/inboxes.svg": "/packs/media/dashboard/assets/images/inboxes-93fdc823fcdf1f10bbb277cefb9de069.svg",
  "media/dashboard/assets/images/lock.svg": "/packs/media/dashboard/assets/images/lock-f25fa6d8307d8bad7ed1e7be31a9197a.svg",
  "media/dashboard/assets/images/woot-logo.svg": "/packs/media/dashboard/assets/images/woot-logo-24d07f13b19c6dd0ca6a64e8ef2220a2.svg",
  "media/fonts/ionicons.eot?v=2.0.1": "/packs/media/fonts/ionicons-19e65b89.eot",
  "media/fonts/ionicons.svg?v=2.0.1": "/packs/media/fonts/ionicons-28df6ee7.svg",
  "media/fonts/ionicons.ttf?v=2.0.1": "/packs/media/fonts/ionicons-dd4781d1.ttf",
  "media/fonts/ionicons.woff?v=2.0.1": "/packs/media/fonts/ionicons-2c159d0d.woff",
  "media/widget/assets/images/defaultUser.png": "/packs/media/widget/assets/images/defaultUser-3df0ec4266329f4981274468e684fa10.png",
  "media/widget/assets/images/logo.svg": "/packs/media/widget/assets/images/logo-a1bb9ce7a33ef8e3b17f28d79a48cb28.svg",
  "media/widget/assets/images/message-send.svg": "/packs/media/widget/assets/images/message-send-415fe9a0a38f50867c359a0c67c22e69.svg",
  "sdk.js": "/packs/js/sdk.js",
  "sdk.js.map": "/packs/js/sdk.js.map",
  "widget.js": "/packs/js/widget-7eee80c25811c89cda9d.js",
  "widget.js.map": "/packs/js/widget-7eee80c25811c89cda9d.js.map"
}
 excluded from capture: DSN not set
F, [2019-11-26T19:45:42.914746 #1] FATAL -- : [193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]   
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] ActionView::Template::Error (Webpacker can't find application in /app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-7eee80c25811c89cda9d.js",
  "application.js.map": "/packs/js/application-7eee80c25811c89cda9d.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-7eee80c25811c89cda9d.js"
      ],
      "js.map": [
        "/packs/js/application-7eee80c25811c89cda9d.js.map"
      ]
    },
    "sdk": {
      "js": [
        "/packs/js/sdk.js"
      ],
      "js.map": [
        "/packs/js/sdk.js.map"
      ]
    },
    "widget": {
      "js": [
        "/packs/js/widget-7eee80c25811c89cda9d.js"
      ],
      "js.map": [
        "/packs/js/widget-7eee80c25811c89cda9d.js.map"
      ]
    }
  },
  "media/dashboard/assets/images/agent.svg": "/packs/media/dashboard/assets/images/agent-aa76bb40e41e0e737cf0e929e8c66d20.svg",
  "media/dashboard/assets/images/canned.svg": "/packs/media/dashboard/assets/images/canned-87a4e4e0032b5b27557c494d9cf1fc2d.svg",
  "media/dashboard/assets/images/channels/facebook.png": "/packs/media/dashboard/assets/images/channels/facebook-4cbc901356e134d542a94a991cdbf4cf.png",
  "media/dashboard/assets/images/channels/facebook_login.png": "/packs/media/dashboard/assets/images/channels/facebook_login-cdbce77d96b5fe3ce2dc084764b4d5e9.png",
  "media/dashboard/assets/images/channels/line.png": "/packs/media/dashboard/assets/images/channels/line-15ace046ed5a35b4304b37d0c077b8e3.png",
  "media/dashboard/assets/images/channels/telegram.png": "/packs/media/dashboard/assets/images/channels/telegram-8967c418781f558f249f84faffbc8e02.png",
  "media/dashboard/assets/images/channels/twitter.png": "/packs/media/dashboard/assets/images/channels/twitter-fef946b8bba756359e2a1e87ccd915ea.png",
  "media/dashboard/assets/images/channels/website.png": "/packs/media/dashboard/assets/images/channels/website-2a4b439c3609ca48ab20c2714333ba77.png",
  "media/dashboard/assets/images/chat.svg": "/packs/media/dashboard/assets/images/chat-55f282b2485b821d927f5228722f48af.svg",
  "media/dashboard/assets/images/fb-badge.png": "/packs/media/dashboard/assets/images/fb-badge-7a4add817f6e7fe207ffe52c428f3305.png",
  "media/dashboard/assets/images/flag.svg": "/packs/media/dashboard/assets/images/flag-10c114599f84077e6edf5f3def7f8855.svg",
  "media/dashboard/assets/images/inboxes.svg": "/packs/media/dashboard/assets/images/inboxes-93fdc823fcdf1f10bbb277cefb9de069.svg",
  "media/dashboard/assets/images/lock.svg": "/packs/media/dashboard/assets/images/lock-f25fa6d8307d8bad7ed1e7be31a9197a.svg",
  "media/dashboard/assets/images/woot-logo.svg": "/packs/media/dashboard/assets/images/woot-logo-24d07f13b19c6dd0ca6a64e8ef2220a2.svg",
  "media/fonts/ionicons.eot?v=2.0.1": "/packs/media/fonts/ionicons-19e65b89.eot",
  "media/fonts/ionicons.svg?v=2.0.1": "/packs/media/fonts/ionicons-28df6ee7.svg",
  "media/fonts/ionicons.ttf?v=2.0.1": "/packs/media/fonts/ionicons-dd4781d1.ttf",
  "media/fonts/ionicons.woff?v=2.0.1": "/packs/media/fonts/ionicons-2c159d0d.woff",
  "media/widget/assets/images/defaultUser.png": "/packs/media/widget/assets/images/defaultUser-3df0ec4266329f4981274468e684fa10.png",
  "media/widget/assets/images/logo.svg": "/packs/media/widget/assets/images/logo-a1bb9ce7a33ef8e3b17f28d79a48cb28.svg",
  "media/widget/assets/images/message-send.svg": "/packs/media/widget/assets/images/message-send-415fe9a0a38f50867c359a0c67c22e69.svg",
  "sdk.js": "/packs/js/sdk.js",
  "sdk.js.map": "/packs/js/sdk.js.map",
  "widget.js": "/packs/js/widget-7eee80c25811c89cda9d.js",
  "widget.js.map": "/packs/js/widget-7eee80c25811c89cda9d.js.map"
}
):
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     23:     <link rel="manifest" href="/manifest.json">
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     24:     <%= csrf_meta_tags %>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     25:     <%= javascript_pack_tag 'application' %>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     26:     <%= stylesheet_pack_tag 'application' %>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     27:   </head>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     28:   <body>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]     29:     <div id="app"></div>
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d]   
[193abb7f-ea9f-4f33-ab1a-7c0d611cf15d] app/views/layouts/vueapp.html.erb:26
```

Looks like the frontend assets are not found / not compiled during build time.

**Comment by sojan-official** [comment]
@pranavrajs  we would need your help here.

**Comment by pranavrajs** [comment]
@kolaente Just an update here, this is happening in production because CSS files are not generated as RAILS_ENV is not available during build time. We will have a fix soon.

>I initially set RAILS_ENV to production because I could not pass the correct database credentials to the container otherwise, it kept using the default for development, which is empty. I assume this is configured in https://github.com/chatwoot/chatwoot/blob/master/config/database.yml#L11.

We have a fix for Postgres password which is merged to master. The latest master should not have that problem.

**Comment by pranavrajs** [comment]
Here is a working docker-compose file I used for production @kolaente 

```
version: '3'
services:
  server: &server
    image: chatwoot/chatwoot
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - SECRET_KEY_BASE=random_key_base
    ports:
      - '3000:3000'
    links:
      - postgres
      - redis


  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot_prod

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'

volumes:
  postgres:
    external: true
  redis:
    external: true
```

**Comment by kolaente** [comment]
@pranavrajs I got it working with this config:

```
version: '3'
services:

  server: 
    image: chatwoot/chatwoot
    restart: unless-stopped
    ports:
      - 3000:3000
      - 5000:5000
      - 3035:3035
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=secret
      - RAILS_ENV=production
      - SECRET_KEY_BASE=6244f432a9ec15b9a6e9b8bc2fcb6ce1

  postgres:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - ./db:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./db:/data/redis
```

However, when I try to create an account, I get this error: 
![image](https://user-images.githubusercontent.com/13721712/70376166-4c5ec980-1906-11ea-8afd-910e73480aa2.png)
How do I set the host?
