### ISSUE TITLE
db:migrate failed on self hosted deployment using helm chat on k8s

### ISSUE THREAD

**Issue by camagenta** [chatwoot/chatwoot#4092]
**Describe the bug**

NoMethodError: undefined method `+' for nil:NilClass
when doing db:migrate

```
Rspec gem is missing. Install it.
Flay gem is missing. Install it.
Rspec gem is missing. Install it.
Loading Installation config
rails aborted!
NoMethodError: undefined method `+' for nil:NilClass
/app/lib/config_loader.rb:83:in `compare_and_save_feature'
/app/lib/config_loader.rb:74:in `reconcile_feature_config'
/app/lib/config_loader.rb:26:in `process'
/app/lib/tasks/db_enhancements.rake:5:in `block in <main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

when i tried add --trace

```
/app/bin # ./rails db:migrate --trace
(in /app)
Rspec gem is missing. Install it.
Flay gem is missing. Install it.
Rspec gem is missing. Install it.
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
** Invoke db:_dump (first_time)
** Execute db:_dump
Loading Installation config
rails aborted!
NoMethodError: undefined method `+' for nil:NilClass
/app/lib/config_loader.rb:83:in `compare_and_save_feature'
/app/lib/config_loader.rb:74:in `reconcile_feature_config'
/app/lib/config_loader.rb:26:in `process'
/app/lib/tasks/db_enhancements.rake:5:in `block in <main>'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:23:in `block in execute'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/hub.rb:158:in `with_background_worker_disabled'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:22:in `execute'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/gems/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/gems/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/gems/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/gems/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/gems/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/command.rb:50:in `invoke'
/gems/ruby/3.0.0/gems/railties-6.1.4.6/lib/rails/commands.rb:18:in `<main>'
/gems/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/gems/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/gems/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/gems/ruby/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
./rails:4:in `<main>'
Tasks: TOP => db:migrate
```

I tried /rake db:chatwoot_prepare

```
/app/bin # ./rake db:chatwoot_prepare
(in /app)
Rspec gem is missing. Install it.
Flay gem is missing. Install it.
Rspec gem is missing. Install it.
Loading Installation config
rake aborted!
NoMethodError: undefined method `+' for nil:NilClass
/app/lib/config_loader.rb:83:in `compare_and_save_feature'
/app/lib/config_loader.rb:74:in `reconcile_feature_config'
/app/lib/config_loader.rb:26:in `process'
/app/lib/tasks/db_enhancements.rake:5:in `block in <main>'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:23:in `block in execute'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/hub.rb:158:in `with_background_worker_disabled'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:22:in `execute'
/app/lib/tasks/db_enhancements.rake:27:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:23:in `block in execute'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/hub.rb:158:in `with_background_worker_disabled'
/gems/ruby/3.0.0/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:22:in `execute'
./rake:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**To Reproduce**

I install in my cluster using this yaml's file

**helm-relase-chatwoot.yaml**
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chatwoot
  namespace: notifikasi
spec:
  interval: 5m
  targetNamespace: notifikasi
  chart:
    spec:
      chart: chatwoot
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: chatwoot
        namespace: notifikasi
      interval: 5m
  values:
    redis:
      enabled: false
      auth:
        password: "redis"
      host: 10.128.236.XXX
      port: 16379
      password: "password"    
```

**help-repository-chatwoot.yaml**
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: chatwoot
  namespace: notifikasi
spec:
  interval: 5m
  url: https://chatwoot.github.io/charts
```

**redis-chatwoot.yaml** (without pv)
```
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
  namespace: notifikasi
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:6.2.6-bullseye  # or just image: redis
        args: ["--requirepass", "$(REDIS_PASS)"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASS
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: rdservice
  namespace: notifikasi
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 16379
      targetPort: 6379
```

ussually we use redis without password, then we try to setup "password" as password

**Expected behavior**

installation success

**Screenshots**

![image](https://user-images.githubusercontent.com/2554004/156209469-457c863f-a55a-4db9-a8e2-f8b65b4c2d29.png)
so far i got this

**Environment**

self hosted installation of Chatwoot using k8s and gitops using flux
https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 98.0.4758.109
