### ISSUE TITLE
Could not connect to Woot Server in Kubernetes Helm

### ISSUE THREAD

**Issue by walejandromt** [chatwoot/chatwoot#4101]
**Describe the bug**

i installed chatwoot with helm for kubernetes in microk8s

**To Reproduce**

firts install chatwoot in kubernetes microk8s with:
Hell Comand install
``` ruby
helm install chatwoot --set env.SECRET_KEY_BASE="123456789" --set env.FRONTEND_URL="https://chatwoot.myhost.com" --set env.MAILER_SENDER_EMAIL="myemail@gmail.com" --set env.SMTP_ADDRESS="smtp.gmail.com"  --set env.SMTP_AUTHENTICATION="login" --set env.SMTP_PASSWORD="123456789" --set env.SMTP_PORT="587" --set env.SMTP_USERNAME="myemail@gmail.com" -f chatwoot-values.yaml chatwoot/chatwoot --namespace chatwoot
```

chatwoot-values.yaml

``` yaml
redis:
  volumePermissions:
    enabled: true
  master:
    persistence: 
      enabled: true
      existingClaim: redis-master-claim

postgresql:
  persistence:
    enabled: true
    existingClaim: postgresql-claim
  volumePermissions:
    enabled: true
```

and when installed its finished i go to website chatwoot.myhost.com and show this screen:
![image](https://user-images.githubusercontent.com/14278594/156401671-3da453fb-68e5-4d9e-82e9-b64cfc82f60e.png)

**Expected behavior**

i try first installation

**Screenshots**

type anything account name:
![image](https://user-images.githubusercontent.com/14278594/156401902-a1da337b-ddf6-41f7-8061-75dbc8264beb.png)

**Browser logs**
![image](https://user-images.githubusercontent.com/14278594/156402069-8dcfebb9-8726-4ebe-9fb8-e4a443bdbbab.png)

![image](https://user-images.githubusercontent.com/14278594/156402103-4a603cec-e555-4651-8fed-d5438d40be98.png)

![image](https://user-images.githubusercontent.com/14278594/156402146-a0c3cfc4-03e4-41dd-9eea-a4826e3213fe.png)

![image](https://user-images.githubusercontent.com/14278594/156402276-e52aeb09-afb8-49e4-9cb8-d5acd57ba505.png)

**Server logs**
![image](https://user-images.githubusercontent.com/14278594/156402780-4be5e6ff-145a-4365-8b6b-8fafccf90d64.png)

**Environment**
 --set env.SECRET_KEY_BASE="123456789"
--set env.FRONTEND_URL="https://chatwoot.myhost.com"
--set env.MAILER_SENDER_EMAIL="myemail@gmail.com"
--set env.SMTP_ADDRESS="smtp.gmail.com"
--set env.SMTP_AUTHENTICATION="login"
--set env.SMTP_PASSWORD="123456789"
--set env.SMTP_PORT="587"
--set env.SMTP_USERNAME="myemail@gmail.com"
