### ISSUE TITLE
Cannot create new users or recieve messages

### ISSUE THREAD

**Issue by JasoonS** [chatwoot/chatwoot#484]
**Describe the bug**

When I try create a new user I get this error displayed on the UI:
`ERR Client sent AUTH, but no password is set`

In the developer console the network request gets this response:
`{"error":"500 error","message":"ERR Client sent AUTH, but no password is set"}`

When I send a message from my UI (that I get from the small generated script tag snippet) the message doesn't go through either (I'm not sure if it is related):
`{"status":500,"error":"Internal Server Error"}`

**To Reproduce**
**To Reproduce**

1. Use the following docker-compose and env file:
Using this docker-compose:
```
version: "3"

services:
  rails:
    image: chatwoot/chatwoot:latest
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    env_file: .env ## Change this file for customized env variables
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "e```xec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  postgres:
    image: postgres:11.6
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres:/data/postgres
    environment:
      - POSTGRES_DB=chatwoot_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
    restart: always
    # volumes:
    #   - redis:/data/redis
    ports:
      - "6379:6379"

volumes:
  postgres:
  redis:
  bundle:
  packs:
  node_modules_rails:
```

And this env file:
```
SECRET_KEY_BASE=testing

#redis config
REDIS_URL=redis://redis:6379
REDIS_PASSWORD=

# Postgres Database config variables
POSTGRES_HOST=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres
RAILS_ENV=development
RAILS_MAX_THREADS=5

MAILER_SENDER_EMAIL=accounts@chatwoot.com
SMTP_PORT=1025
SMTP_DOMAIN=chatwoot.com
SMTP_ADDRESS=mailhog

#misc
FRONTEND_URL=http://0.0.0.0:3000
ACTIVE_STORAGE_SERVICE=local

# Credentials to access sidekiq dashboard in production
SIDEKIQ_AUTH_USERNAME=test@test.com
SIDEKIQ_AUTH_PASSWORD=test
```

2. Then run `docker-compose up` and `docker-compose run --rm rails bundle exec rails db:reset`.

3. Visit http://localhost:3000 . login with default credentials
user name: john@acme.inc
password: 123456

4. Once logged in go to "settings" then "+ Add Agent". Full in any details. And click submit. This step didn't create a new agent for me. It rather threw an internal server error:
`{"error":"500 error","message":"ERR Client sent AUTH, but no password is set"}`

 How do I set a password? What does this error mean?

**Expected behavior**

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: firefox dev edition
- Version: 73.0b12 (64-bit)

**Additional context**
The "curl" of the request when trying to add an agent is as follows: `curl 'http://localhost:3000/api/v1/agents' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:3000/app/settings/agents/list' -H 'access-token: 3sUb2mqFG_7tDaDmCse8GQ' -H 'token-type: Bearer' -H 'client: QEy1TOleAcm_pfj4KqkmMQ' -H 'expiry: 1582451745' -H 'uid: john@acme.inc' -H 'Content-Type: application/json;charset=utf-8' -H 'Origin: http://localhost:3000' -H 'Connection: keep-alive' -H 'Cookie: crisp-client%2Fsession%2F6b881313-dab6-4e17-b29e-b1e39eb58400=session_65c30101-895d-45d5-9bff-cce5d4aed6ea; auth_data={%22access-token%22:%223sUb2mqFG_7tDaDmCse8GQ%22%2C%22cache-control%22:%22max-age=0%2C%20private%2C%20must-revalidate%22%2C%22client%22:%22QEy1TOleAcm_pfj4KqkmMQ%22%2C%22content-type%22:%22application/json%3B%20charset=utf-8%22%2C%22etag%22:%22W/%5C%22e3c465f080bb9ed067caf56b7bc9cb1a%5C%22%22%2C%22expiry%22:%221582451745%22%2C%22token-type%22:%22Bearer%22%2C%22transfer-encoding%22:%22chunked%22%2C%22uid%22:%22john@acme.inc%22%2C%22x-frame-options%22:%22ALLOWALL%22%2C%22x-request-id%22:%224134dbc3-52ab-4492-b8a4-8b85394e5ac2%22%2C%22x-runtime%22:%220.296170%22}; user={%22id%22:1%2C%22email%22:%22john@acme.inc%22%2C%22provider%22:%22email%22%2C%22name%22:%22John%22%2C%22account_id%22:1%2C%22uid%22:%22john@acme.inc%22%2C%22nickname%22:null%2C%22pubsub_token%22:%22aCZEnagexLnJRTaRQmUFTbbr%22%2C%22role%22:%22administrator%22%2C%22inviter_id%22:null%2C%22confirmed%22:true}; io=fSfTeIVkjd_DCWNvAAAA; _chatwoot_session=hZz9QW49vib87ia6zo48OW5m2pDvUeLRvRPLPtGKJIGdwt7papINVRnIs5bsWYSHPJdpvkWpxvj1Lh5TgEllDEeupjv4gN96EFvciKVOXZ20iSNhxW25QTpehy%2Fv6s08tIO7vPrpGIDN2VF7ziqiuI%2B01erySUasqgXg2ajuhwxZd93H7Bdj0xJPz%2Fb0S6KLB%2Bl2JIklOQ1PuTABweMgT9ZCL9berj%2BSp9M53uB9G%2Fo6KlpwLln6yH86L5JsFyYnLmoxZm%2B6YpYLczFWO1nA87hBWmPBoQxXoGGZ%2Fmyc4pBmEWk1qu0RfwGJs5UzmWtoEGZSKbKW%2B3gaGR4PbjEHqoe6x4RzYYk0uvES%2Fbi5CVi46cpfz9hYPiajqYg3aNjahgCyMpNKQIPe--tBbo%2Fwil0njXyDzS--A3Lf%2B6P%2BbtscjZ77MIatrA%3D%3D; cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiJlNDY4MjhmYy05YTgyLTQ2OGQtYmYyNy0wMDJlOGNkYjA2ZWIiLCJpbmJveF9pZCI6Mn0.bpG30-F2gKyQEGEn-E-TqF5qNguAPETPjZNnDxVur2w' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data '{"name":"Jason","email":"jason+nthsntmttmmnt@wildcards.world","role":"agent"}'`

I tried setting it up with a SMTP server from my AWS account. I may have configured that wrong, but that didn't work either.

Are there debug flags you want me to run it with in the future?

**Comment by pranavrajs** [comment]
`ERR Client sent AUTH, but no password is set`

This looks to be an error from Redis, Could you please cross check the redis password and the one which you set in REDIS_PASSWORD is correct.

If you are using redis image from docker the following would be the correct configuration
```
 redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'
```
