### ISSUE TITLE
No support for Redis Cluster?

### ISSUE THREAD

**Issue by voarsh2** [chatwoot/chatwoot#5015]
I migrated the data from the internal standalone Redis cluster because it's not highly available, I found that the environment variables didn't update the secret for the external password/host and url, saw things like "not set" etc.

```
redis:
  auth:
    password: wpkvmwdjBr
  enabled: false
  password: wpkvmwdjBr
  host: 10.43.171.72
  master:
    persistence:
      enabled: false
  nameOverride: chatwoot-redis
```

When setting the proper secret settings manualy, it appears Chatwoot doesn't play nice with a cluster (not replication, built in):
```
Booting Sidekiq 6.4.1 with redis options {:url=>"redis://:REDACTED@10.43.171.72:6379", :password=>"REDACTED", :reconnect_attempts=>2, :network_timeout=>5}
--
Mon, Jul 11 2022 5:25:31 pm | 2022-07-11T16:25:31.962Z pid=1 tid=655 WARN: Redis::CommandError: MOVED 1192 10.42.42.112:6379
```
https://stackoverflow.com/questions/64374113/replyerror-moved-error-after-connecting-to-redis-cluster-aws
