### ISSUE TITLE
Saving chatwoot configuration in a docker container

### ISSUE THREAD

**Issue by AndrewNeborsky** [chatwoot/chatwoot#5673]
**Is your enhancement request related to a problem? Please describe.**
In my project, chatwoot runs with docker-compose.production.yml. Recently, it became necessary to change rate limits, but after restarting the container, the changes return to the default.

**Describe the solution you'd like**
Configuration changes don't revert back to default values after restarting a container.

**Describe alternatives you've considered**
I use bind mount for mounting rack_attack.rb into a container, but I would like to have an official solution to this problem.

**Additional context**
As a solution I can suggest to save the configuration in a docker volume.
```yml
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - &storage_volume /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - *storage_volume
      - rack_attack_config:/app/config/initializers/rack_attack
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
.
.
.
volumes:
  rack_attack_config:
```

**Comment by sojan-official** [comment]
```
env_file: .env ## Change this file for customized env variables 
```
You can create a `.env` file and customize the values 

alternatively you can pass it directly in docker compose 

```
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - &storage_volume /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - *storage_volume
      - rack_attack_config:/app/config/initializers/rack_attack
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - ENABLE_RACK_ATTACK=false
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

```
