### ISSUE TITLE
Docker Swarm deployment fails

### ISSUE THREAD

**Issue by whiteyhat** [chatwoot/chatwoot#625]
**Describe the bug**
When following your guidelines for the docker deployment it fails when creating a docker swarm stack

**To Reproduce**
Steps to reproduce the behaviour:
1. Docker-compose set up:
```yaml
networks:
  monitoring:
    external: true
  web:
    external: true
services:
  app:
    command:
    - bundle
    - exec
    - rails
    - s
    - -p
    - '3000'
    - -b
    - 0.0.0.0
    deploy:
      labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.docker.network=web
      - traefik.frontend.redirect.entryPoint=http
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.rule=Host:chatwoot.localhost
      - traefik.backend.loadbalancer.swarm=true
      - traefik.backend.loadbalancer.stickiness=false
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1m
        failure_action: rollback
        order: start-first
        parallelism: 1
    entrypoint: docker/entrypoints/rails.sh
    environment:
      ACTIVE_STORAGE_SERVICE: local
      AWS_ACCESS_KEY_ID: ''
      AWS_REGION: ''
      AWS_SECRET_ACCESS_KEY: ''
      CHARGEBEE_API_KEY: ''
      CHARGEBEE_SITE: ''
      CHARGEBEE_WEBHOOK_PASSWORD: ''
      CHARGEBEE_WEBHOOK_USERNAME: ''
      CHATWOOT_VERSION: latest
      DOMAIN: chatwoot.localhost
      DOMAIN_ENTRYPOINT: http
      ENABLE_ACCOUNT_SIGNUP: "true"
      ENABLE_BILLING: ''
      FB_APP_ID: ''
      FB_APP_SECRET: ''
      FB_VERIFY_TOKEN: ''
      FRONTEND_URL: http://0.0.0.0:3000
      MAILER_SENDER_EMAIL: accounts@chatwoot.com
      NODE_ENV: production
      POSTGRES_DATA: ./.data/db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_VERSION: '11.6'
      RAILS_ENV: production
      RAILS_MAX_THREADS: '5'
      REDIS_DATA: ./.data/redis
      REDIS_PASSWORD: password
      REDIS_URL: redis://redis:6379
      REDIS_VERSION: alpine
      S3_BUCKET_NAME: ''
      SECRET_KEY_BASE: 2bdd928a824461cbd5e5ebfa90604b03a3b7f2e5da2c9a9c83a54a7fdc20c78b7ec1b4587bb40613439bccbfa9c1e3910946c0c038dbdfd18331870c32e11c84
      SENTRY_DSN: ''
      SIDEKIQ_AUTH_PASSWORD: ''
      SIDEKIQ_AUTH_USERNAME: ''
      SMTP_ADDRESS: mailhog
      SMTP_AUTHENTICATION: ''
      SMTP_DOMAIN: chat.localhost
      SMTP_ENABLE_STARTTLS_AUTO: ''
      SMTP_PASSWORD: ''
      SMTP_PORT: '1025'
      SMTP_USERNAME: ''
      TWITTER_APP_ID: ''
      TWITTER_CONSUMER_KEY: ''
      TWITTER_CONSUMER_SECRET: ''
      TWITTER_ENVIRONMENT: ''
    image: chatwoot/chatwoot:latest
    networks:
      default: null
      web: null
  postgres:
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    image: postgres:11.6
    networks:
      default: null
      monitoring: null
    volumes:
    - /Users/whiteyhat/Documents/GitHub/docker.cloud/chatwoot/.data/db:/var/lib/postgresql/data:rw
  redis:
    command:
    - sh
    - -c
    - redis-server --requirepass "password"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    image: redis:alpine
    networks:
      default: null
    volumes:
    - /Users/whiteyhat/Documents/GitHub/docker.cloud/chatwoot/.data/redis:/data:rw
  sidekiq:
    command:
    - bundle
    - exec
    - sidekiq
    - -C
    - config/sidekiq.yml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 1m
        failure_action: rollback
        order: start-first
        parallelism: 1
    environment:
      ACTIVE_STORAGE_SERVICE: local
      AWS_ACCESS_KEY_ID: ''
      AWS_REGION: ''
      AWS_SECRET_ACCESS_KEY: ''
      CHARGEBEE_API_KEY: ''
      CHARGEBEE_SITE: ''
      CHARGEBEE_WEBHOOK_PASSWORD: ''
      CHARGEBEE_WEBHOOK_USERNAME: ''
      CHATWOOT_VERSION: latest
      DOMAIN: chatwoot.localhost
      DOMAIN_ENTRYPOINT: http
      ENABLE_ACCOUNT_SIGNUP: "true"
      ENABLE_BILLING: ''
      FB_APP_ID: ''
      FB_APP_SECRET: ''
      FB_VERIFY_TOKEN: ''
      FRONTEND_URL: http://0.0.0.0:3000
      MAILER_SENDER_EMAIL: accounts@chatwoot.com
      NODE_ENV: production
      POSTGRES_DATA: ./.data/db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_VERSION: '11.6'
      RAILS_ENV: production
      RAILS_MAX_THREADS: '5'
      REDIS_DATA: ./.data/redis
      REDIS_PASSWORD: password
      REDIS_URL: redis://redis:6379
      REDIS_VERSION: alpine
      S3_BUCKET_NAME: ''
      SECRET_KEY_BASE: 2bdd928a824461cbd5e5ebfa90604b03a3b7f2e5da2c9a9c83a54a7fdc20c78b7ec1b4587bb40613439bccbfa9c1e3910946c0c038dbdfd18331870c32e11c84
      SENTRY_DSN: ''
      SIDEKIQ_AUTH_PASSWORD: ''
      SIDEKIQ_AUTH_USERNAME: ''
      SMTP_ADDRESS: mailhog
      SMTP_AUTHENTICATION: ''
      SMTP_DOMAIN: chat.localhost
      SMTP_ENABLE_STARTTLS_AUTO: ''
      SMTP_PASSWORD: ''
      SMTP_PORT: '1025'
      SMTP_USERNAME: ''
      TWITTER_APP_ID: ''
      TWITTER_CONSUMER_KEY: ''
      TWITTER_CONSUMER_SECRET: ''
      TWITTER_ENVIRONMENT: ''
    image: chatwoot/chatwoot:latest
    networks:
      default: null
version: '3.4'

```
2. Deploy stack
3. Services are up and running
4. Trying to sign up fails
5. See error below
![Captura de pantalla 2020-03-19 a las 12 36 32](https://user-images.githubusercontent.com/31220861/77063615-4df85d00-69de-11ea-9f78-ca1c730eb989.png)

**Expected behaviour**
No errors on sign up and the system should work

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
