### ISSUE TITLE
[CW-1965] [Docker] Upgrade from v2.13.1 to 2.14.0 FAILS with sidekiq.

### ISSUE THREAD

**Issue by politsin** [chatwoot/chatwoot#6499]
**Describe the bug**

I got en error while do ` docker-compose up`
```log
...
rails_1    | If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
rails_1    | + BUNDLE='bundle check'
rails_1    | + bundle check
sidekiq_1  | bundler: failed to load command: sidekiq (/gems/ruby/3.1.0/bin/sidekiq)
sidekiq_1  | /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
sidekiq_1  |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
sidekiq_1  |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
sidekiq_1  |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/client.rb:3:in `require'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/client.rb:3:in `<top (required)>'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:7:in `require'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:7:in `<top (required)>'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:11:in `require'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:11:in `<top (required)>'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/bin/sidekiq:7:in `require_relative'
sidekiq_1  |    from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/bin/sidekiq:7:in `<top (required)>'
sidekiq_1  |    from /gems/ruby/3.1.0/bin/sidekiq:25:in `load'
sidekiq_1  |    from /gems/ruby/3.1.0/bin/sidekiq:25:in `<top (required)>'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
sidekiq_1  |    from /usr/local/bundle/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
sidekiq_1  |    from /usr/local/bundle/bin/bundle:25:in `load'
sidekiq_1  |    from /usr/local/bundle/bin/bundle:25:in `<main>'
rails_1    | The Gemfile's dependencies are satisfied
rails_1    | + exec bundle exec rails s -p 3000 -b 0.0.0.0
chatwoot_base_1 exited with code 0
chatwoot_sidekiq_1 exited with code 1
rails_1    | /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
rails_1    |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
rails_1    |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
rails_1    |    from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<main>'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/activesupport-6.1.7.1/lib/active_support.rb:26:in `<main>'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/command.rb:3:in `<main>'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/railties-6.1.7.1/lib/rails/commands.rb:3:in `<main>'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from /gems/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1    |    from bin/rails:4:in `<main>'

```

**Environment**
- [x ] Self-hosted
- - [x ] Linux 3.16.0-5-amd64 / Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64

**Docker** 
- Docker version 18.03.1-ce, build 9ee9f40
- docker-compose version 1.21.2, build a133471
- docker-py version: 3.3.0
- CPython version: 3.6.5
- OpenSSL version: OpenSSL 1.0.1t  3 May 2016

### 1 One server updated without any problems
Linux 5.4.0-100-generic https://github.com/chatwoot/chatwoot/issues/113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

### 2 The second got the problem that is described by the message above.
Linux 3.16.0-5-amd64 https://github.com/chatwoot/chatwoot/pull/1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64
Docker version 18.03.1-ce, build 9ee9f40

```yml
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:v2.14.0
    env_file: .env 
    volumes:
      - ./data/storage:/app/storage

  rails:
    <<: *base
    external_links:
      - postgre-xx-chat:postgres
      - redis-xx-chat:redis
    networks:
      - chatwoot
    ports:
      - '0.0.0.0:3030:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    external_links:
      - postgre-xx-chat:postgres
      - redis-xx-chat:redis
    networks:
      - chatwoot
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

networks:
 chatwoot:
    external: true
```

<sub>[CW-1965](https://linear.app/chatwoot/issue/CW-1965/[docker]-upgrade-from-v2131-to-2140-fails-with-sidekiq)</sub>
