### ISSUE TITLE
Chat doesn't update with reply 

### ISSUE THREAD

**Issue by mxsxs2** [chatwoot/chatwoot#8818]
### Describe the bug

We run a self hosted Chatwoot in Kubernetes installed with helm chart. 

It used to work well up until 3.0 (we use 3.5.1 now). Since the update everything works well for about 7 days. Then when we receive a message form a user we get the email and we can see the message in the chat. When we send the reply to the user it shows as sent but the user does not receive it and if the user writes more messages we don't receive it either. If the user refreshes the webpage then they will see all the messages but not new ones. It is the same on the agent side as well. 

The only solution I found for this is to remove the chart and reinstall it with the same config.  After that it works okay for 7 days and  the issue starts again.

Here is a recording that may explain it better:
![20240130_135306](https://github.com/chatwoot/chatwoot/assets/13612429/86a2a96d-0e7f-41df-b0b2-07f72a2ae823)

Thanks!

### To Reproduce

1. Install helm chart
2. Wait a week
3. Chats are not updating

### Expected behavior

Chats updating when a message sent

### Environment

Kubernetes

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Chrome 120.0.6099.225

### Docker (if applicable)

docker version:

> Client:
>  Version:           19.03.6
>  API version:       1.40
>  Go version:        go1.12.17
>  Git commit:        369ce74a3c
>  Built:             Fri Dec 18 12:21:44 2020
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server:
>  Engine:
>   Version:          19.03.6
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.17
>   Git commit:       369ce74a3c
>   Built:            Thu Dec 10 13:23:49 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.3.3-0ubuntu1~18.04.4
>   GitCommit:
>  runc:
>   Version:          spec: 1.0.1-dev
>   GitCommit:
>  docker-init:
>   Version:          0.18.0
>   GitCommit:

kubectl version:

> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

helm -n chatwoot list:
> NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
> chatwoot        chatwoot        1               2024-01-30 15:11:53.475189328 +0100 CET deployed        chatwoot-1.1.7  v3.5.1

### Additional context

My config file for the chart is:

```
postgresql:
  primary:
    persistence:
      storageClass: chatwoot-postgresql-standard
      size: 8Gi
redis:
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false

services:
  type: ClusterIP

ingress:
  enabled: ture
  ingressClassName: nginx
  annotations:
    nginx.org/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    nginx.org/location-snippets: |
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-Proto https;
  hosts:
    - host: xxxxxxxxxx
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: chatwoot
            port:
              number: 3000

env:
  FRONTEND_URL: 'https://xxxxxxxxxxx'
  DISABLE_TELEMETRY: true
  FORCE_SSL: false
  SMTP_ADDRESS: xxxxxxxxx
  SMTP_PORT: xxxxxxx
  MAILER_SENDER_EMAIL: xxxxxxxxxxx
  SMTP_USERNAME: xxxxxxxxxxxx
  SMTP_PASSWORD: xxxxxxxxx
  SMTP_AUTHENTICATION: login
  SMTP_ENABLE_STARTTLS_AUTO: true
  ACTIVE_STORAGE_SERVICE: s3_compatible
  STORAGE_BUCKET_NAME: chatwoot-assets
  STORAGE_ACCESS_KEY_ID: xxxxxxxxxxxxx
  STORAGE_SECRET_ACCESS_KEY: xxxxxxxxxxx
  STORAGE_REGION: localCluster
  STORAGE_ENDPOINT: https://xxxxxxxx
  STORAGE_FORCE_PATH_STYLE: true
```
