### ISSUE TITLE
Support for IPv6 in Chatwoot Helm Chart Deployment

### ISSUE THREAD

**Issue by albert-suryanto** [chatwoot/chatwoot#8826]
### Is your feature or enhancement related to a problem? Please describe.

A significant challenge we're facing is the integration of Chatwoot, particularly due to its current limitation in the Helm chart (web-deployment.yaml), which only supports IPv4 (specified as 0.0.0.0)

Our infrastructure primarily relies on IPv6, and the lack of IPv6 support in Chatwoot's Helm chart deployment is hindering our ability to effectively incorporate Chatwoot into our IPv6-based network environment. This limitation is a crucial barrier for seamless integration and full utilization of Chatwoot in our setup.

### Describe the solution you'd like

Make an update in Chatwoot Helm chart to support IPv6 addressing. This can be achieved by modifying the `web-deployment.yaml` to allow configuration for IPv6 addresses or by automatically detecting and adapting to the network environment (IPv4 or IPv6). The ideal solution would provide flexibility in specifying the IP version in the deployment configurations."

Suggestion
`web-deployment.yaml`
```
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - args:
            - bundle
            - exec
            - rails
            - s
            - -p
            - {{ .Values.services.internalPort | quote}}
            - -b
            - {{ .Values.services.internalHost | quote}}
```
and in `values.yaml`, we can specify internalHost value to be either `0.0.0.0` (for IPv4) and `::` (for IPv6)

Currently (on v1.1.7)
```
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - args:
            - bundle
            - exec
            - rails
            - s
            - -p
            - {{ .Values.services.internalPort | quote}}
            - -b
            - 0.0.0.0
```
