### ISSUE TITLE
exec docker/entrypoints/rails.sh: exec format error

### ISSUE THREAD

**Issue by ahmedrowaihi** [chatwoot/chatwoot#9009]
### Describe the bug

I am running the compose stack using portainer on my raspberry pi
```
OS: Debian GNU/Linux 12 (bookworm) aarch64 
Host: Raspberry Pi 4 Model B Rev 1.4 
Kernel: 6.1.0-rpi8-rpi-v8 
Shell: bash 5.2.15 
CPU: (4) @ 1.800GHz 
```
postgres, redis containers are running with no problems

but seems something odd about the ```irb```  in the chatwoot based containers

### ERROR:
```
exec docker/entrypoints/rails.sh: exec format error
```

### To Reproduce

1. use portainer on raspberry pi | image: ```portainer/portainer-ce:2.19.4-alpine```
2. create custom stack
3. deploy stack with this compose yml
compose yaml
```yaml
version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: stack.env ## Change this file for customized env variables
    environment:
      - REDIS_URL=redis://redis:6378  # Override REDIS_URL with the new Redis port
      - POSTGRES_PORT=5433  # Adjust the PostgreSQL port
    volumes:
      - chatwoot_storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '127.0.0.1:5433:5432'  # Change the host port to 5433
    volumes:
      - chatwoot_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=chatwoot

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: stack.env
    volumes:
      - chatwoot_cache:/data
    ports:
      - '127.0.0.1:6378:6379'  # Change the host port to 6378
      
volumes:
  chatwoot_storage:
  chatwoot_pg:
  chatwoot_cache:
```
4. observe

### Expected behavior

should run :')

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Debian GNU/Linux 12 (bookworm) aarch64
