### ISSUE TITLE
How to update chatwoot correctly with docker? version 3.7.0 to 3.8.0?

### ISSUE THREAD

**Issue by RDX777** [chatwoot/chatwoot#9319]
### Describe the bug

When I update from one version to another, the chatwoot system stops receiving messages sent, via evolution api, to start working again, it is necessary to recreate the database. im using a external postgres database and a external evolution api server. 

### To Reproduce

Using version 3.7.0, I ran these dockerfiles:

**dockercompose.yml:**

```
services:
  base: &base
    build:
      context: ./
    env_file: .env
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
      - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_SSL=${SMTP_SSL}
      - DIRECT_UPLOADS_ENABLED=true
    volumes:
      - ../data/chatwoot:/app/storage
    networks:
      - chatbot-net

  rails:
    <<: *base
    # ports:
    #   - "3000:3000"
    restart: always
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    networks:
      - chatbot-net

  sidekiq:
    <<: *base
    restart: always
    # cpus: 3
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    networks:
      - chatbot-net

volumes:
  chatwoot_data:

networks:
  chatbot-net:
    name: chatbot-net
    driver: bridge
```

**Dockerfile:**

```
FROM chatwoot/chatwoot:latest

RUN cat /etc/os-release
ENV TZ=America/Sao_Paulo
RUN apk update
RUN apk add postgresql-dev
```

In terminal:

```
docker-compose -f ./chatwoot/docker-compose.yml up -d --build
docker-compose -f ./chatwoot/docker-compose.yml run --rm rails bundle exec rails db:migrate
docker-compose -f ./chatwoot/docker-compose.yml run --rm rails bundle exec rails db:chatwoot_prepare
```

### Expected behavior

Using a version 3.8.0 i cant recive any message from evolutionapi.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

ubuntu

### Browser and version

mozila firefox
