### ISSUE TITLE
Can not access api.telegram.org or any other domains

### ISSUE THREAD

**Issue by zou-yu** [chatwoot/chatwoot#9518]
### Describe the bug

When I try to add a new telegram channel, I found my k8s(self-hosted) pods cannot access telegram apis.
<img width="457" alt="image" src="https://github.com/chatwoot/chatwoot/assets/26666752/561b0680-47b9-4bb3-97e3-140c8bf8778d">

### To Reproduce

The log of pod chatwoot-web-xxx show shows that:

```
F, [2024-05-22T10:37:00.172504 #1] FATAL -- : [45bc2835-18a5-4895-a430-9bfc703c5965]   
[45bc2835-18a5-4895-a430-9bfc703c5965] SocketError (Failed to open TCP connection to api.telegram.org:443 (getaddrinfo: Name has no usable address)):
```

Then I enter the k8s pod using `kubectl exec -it  chatwoot-web-xx -- sh`,
nslookup works:
```
/app # nslookup api.telegram.org
Server:         10.43.0.10
Address:        10.43.0.10:53

Non-authoritative answer:
Name:   api.telegram.org
Address: 2001:67c:4e8:f004::9

Non-authoritative answer:
Name:   api.telegram.org
Address: 149.154.167.220
```
ping the resolved ip also works:
```
/app # ping 149.154.167.220
PING 149.154.167.220 (149.154.167.220): 56 data bytes
64 bytes from 149.154.167.220: seq=0 ttl=51 time=248.580 ms
```
but can not ping api.telegram.org:
```
/app # ping api.telegram.org
ping: bad address 'api.telegram.org'
```

And I wonder if my k8s went wrong, so I do the follow steps:

It can access api.telegram.org using busybox
```
kubectl apply -f busybox.yaml
kubectl exec -it busybox -- ping api.telegram.org
# works
```

```yml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

But I replace the image `busybox` to `chatwoot/chatwoot`, it doesn't work, cannot access api.telegram.org
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: chatwoot/chatwoot
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
 ```

So it seems like something wrong with image chatwoot/chatwoot

### Environment

Kubernetes

### Cloud Provider

None

### Platform

Browser
