### ISSUE TITLE
Sendgrid Email Send Failed

### ISSUE THREAD

**Issue by the-mgi** [chatwoot/chatwoot#9978]
### Describe the bug

AWS EKS deployment

Timeout to open TCP connection to smtp.sendgrid.net:587 

### To Reproduce

try sending outgoing email using sendgrid smtp api
my sender identity is already created in the sendgrid
i've verified my domain xx.xx.com, and then a new identity help@xx.xx.com was created which was verified
this is my env
```yml
      MAILER_SENDER_EMAIL: help@xx.xx.com
      SMTP_DOMAIN: xx.xx.com
      SMTP_ADDRESS: smtp.sendgrid.net
      SMTP_PORT: 587
      SMTP_USERNAME: apikey
      SMTP_PASSWORD: SG.xx.xxx
      SMTP_AUTHENTICATION: plain
      SMTP_ENABLE_STARTTLS_AUTO: true
      SMTP_OPENSSL_VERIFY_MODE: none
```

### Expected behavior

email should be sent

### Environment

Kubernetes

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

macOS
